### ISSUE TITLE
encoder: invalid argument

### ISSUE THREAD

**Issue by kuronyago** [hraban/opus#39] opened 2021-04-23 20:12 UTC
hello, please help me
returns the same error - `opus: invalid argument`
what am I doing wrong?

```
package main

import (
	opus "gopkg.in/hraban/opus.v2"
)

func main() {
	encoder, err := opus.NewEncoder(48000, 2, opus.AppAudio)
	if err != nil {
		println(err.Error())
		return
	}

	pcm := make([]float32, 512)

	data := make([]byte, 256)

	n, err := encoder.EncodeFloat32(pcm, data)
	if err != nil {
		println(err.Error())
		return
	}

	println(len(pcm[:n]))
}
```

**Comment by hraban** [comment] 2021-04-24 08:08
The error comes from the encode step, which is encoding uninitialised PCM data. Do you have pcm float data somewhere to encode? If you can't find any; have a look at stream_test.go and testdata/speech_8.wav for how to get PCM data from a .wav file. Another way to generate raw PCM data is shown in utils_test.go; the addSine function will add a sine wave to a set of PCM samples.

Note: PCM data = raw audio samples. Audio is a sequence of air pressure measurements, at very high frequency. You can plot the PCM data in Excel to see the waveform, e.g. https://github.com/hraban/opus/pull/18#discussion_r178431791 . Opus is a library to turn that waveform into a dense series of bytes, so when you decode it, you get more or less the original waveform back. Have a look at the test files for examples of use, and what kind of data you can pass in.

I'm closing this issue since it's not a bug in the opus wrapper code, but a support ticket. Feel free to ask more questions after you've looked at the test files and we'll see if we can sort this out :)

**Closed as completed** 2021-04-24 20:51 UTC
